export const colombiaData = {
    "Amazonas": ["Leticia", "Puerto Nariño", "La Chorrera", "Tarapacá"],
    "Antioquia": ["Medellín", "Bello", "Itagüí", "Envigado", "Apartadó", "Rionegro", "Caucasia", "Turbo", "Sabaneta", "La Estrella", "Caldas", "Copacabana", "Girardota", "Marinilla", "Guarne", "La Ceja", "Carmen de Viboral", "Yarumal", "Santa Fe de Antioquia"],
    "Arauca": ["Arauca", "Arauquita", "Saravena", "Tame", "Fortul", "Puerto Rondón", "Cravo Norte"],
    "Atlántico": ["Barranquilla", "Soledad", "Malambo", "Sabanalarga", "Baranoa", "Galapa", "Puerto Colombia", "Santo Tomás", "Sabanagrande"],
    "Bolívar": ["Cartagena", "Magangué", "Turbaco", "El Carmen de Bolívar", "Arjona", "Mompox", "San Juan Nepomuceno", "Maria La Baja"],
    "Boyacá": ["Tunja", "Duitama", "Sogamoso", "Chiquinquirá", "Paipa", "Villa de Leyva", "Puerto Boyacá", "Moniquirá", "Nobsa", "Samacá"],
    "Caldas": ["Manizales", "La Dorada", "Chinchiná", "Villamaría", "Riosucio", "Anserma", "Supía", "Neira", "Salamina"],
    "Caquetá": ["Florencia", "San Vicente del Caguán", "Cartagena del Chairá", "Puerto Rico", "El Doncello"],
    "Casanare": ["Yopal", "Aguazul", "Villanueva", "Paz de Ariporo", "Tauramena", "Monterrey", "Maní"],
    "Cauca": ["Popayán", "Santander de Quilichao", "Puerto Tejada", "Piendamó", "El Tambo", "Patía", "Miranda", "Corinto"],
    "Cesar": ["Valledupar", "Aguachica", "Agustín Codazzi", "Bosconia", "Curumaní", "La Jagua de Ibirico", "El Copey"],
    "Chocó": ["Quibdó", "Istmina", "Tadó", "Condoto", "Bahía Solano", "Nuquí", "Acandí"],
    "Córdoba": ["Montería", "Santa Cruz de Lorica", "Sahagún", "Cereté", "Montelíbano", "Planeta Rica", "Tierralta", "Ciénaga de Oro"],
    "Cundinamarca": ["Bogotá D.C.", "Soacha", "Zipaquirá", "Fusagasugá", "Facatativá", "Chía", "Mosquera", "Madrid", "Funza", "Cajicá", "Girardot", "Villeta", "La Mesa", "Tocancipá", "Sopó", "Cota", "Tenjo", "Tabio"],
    "Guainía": ["Inírida", "Barrancominas"],
    "Guaviare": ["San José del Guaviare", "Calamar", "El Retorno", "Miraflores"],
    "Huila": ["Neiva", "Pitalito", "Garzón", "La Plata", "Campoalegre", "San Agustín", "Gigante", "Rivera"],
    "La Guajira": ["Riohacha", "Maicao", "Uribia", "Manaure", "San Juan del Cesar", "Fonseca", "Barrancas", "Villanueva"],
    "Magdalena": ["Santa Marta", "Ciénaga", "Zona Bananera", "Plato", "Fundación", "El Banco", "Aracataca", "Pivijay"],
    "Meta": ["Villavicencio", "Acacías", "Granada", "Puerto López", "San Martín", "Cumaral", "Puerto Gaitán"],
    "Nariño": ["Pasto", "Tumaco", "Ipiales", "La Unión", "Samaniego", "Túquerres", "Barbacoas"],
    "Norte de Santander": ["Cúcuta", "Ocaña", "Villa del Rosario", "Los Patios", "Pamplona", "Tibú", "El Zulia", "Chinácota"],
    "Putumayo": ["Mocoa", "Puerto Asís", "Orito", "Sibundoy", "Villagarzón", "Puerto Guzmán"],
    "Quindío": ["Armenia", "Calarcá", "Montenegro", "La Tebaida", "Quimbaya", "Circasia", "Salento", "Filandia"],
    "Risaralda": ["Pereira", "Dosquebradas", "Santa Rosa de Cabal", "La Virginia", "Belén de Umbría", "Marsella"],
    "San Andrés y Providencia": ["San Andrés", "Providencia"],
    "Santander": ["Bucaramanga", "Floridablanca", "Barrancabermeja", "Girón", "Piedecuesta", "San Gil", "Socorro", "Barbosa", "Vélez", "Cimitarra"],
    "Sucre": ["Sincelejo", "Corozal", "San Marcos", "Tolú", "Sampués", "San Onofre"],
    "Tolima": ["Ibagué", "Espinal", "Melgar", "Chaparral", "Líbano", "Mariquita", "Honda", "Flandes", "Guamo"],
    "Valle del Cauca": ["Cali", "Buenaventura", "Palmira", "Tuluá", "Buga", "Cartago", "Jamundí", "Yumbo", "Candelaria", "Florida", "Pradera", "Zarzal", "Roldanillo", "Sevilla"],
    "Vaupés": ["Mitú", "Carurú", "Taraira"],
    "Vichada": ["Puerto Carreño", "La Primavera", "Santa Rosalía", "Cumaribo"]
};

export const departments = Object.keys(colombiaData).sort();
